services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    env_file:
      - .env
    container_name: "zookeeper-service"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ${ZOOKEEPER_OUTSIDE_PORT}:2181

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    env_file:
      - .env
    container_name: "kafka-service"
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_OUTSIDE_PORT}:${KAFKA_OUTSIDE_PORT}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_OUTSIDE_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    env_file:
      - .env
    container_name: "kafka-ui-service"
    ports:
      - ${KAFKA_UI_OUTSIDE_PORT}:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    env_file:
      - .env
    ports:
      - ${NOTIFICATION_SERVICE_PORT}:8080