FROM golang:1.23 AS build

RUN apt update && apt install -y protobuf-compiler
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
ENV PATH="$PATH:$(go env GOPATH)/bin"

COPY go.mod go.sum /src/
COPY proto /src/proto
COPY api /src/api

ENV CGO_ENABLED=0
RUN cd /src && go build -o /api api/main.go

FROM alpine:3.20

COPY --from=build /api /api

ENTRYPOINT [ "/api" ]