server:
  port: ${NOTIFICATION_SERVICE_PORT}

spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    listener:
      ack-mode: record
    admin:
      auto-create: false

KAFKA_HOST: ${KAFKA_OUTSIDE_HOST}
KAFKA_PORT: ${KAFKA_OUTSIDE_PORT}